version: '3'
# Development evironment
services:
  backend:
    depends_on:
      - db
    build:
      context: ./dockerfiles
      dockerfile: backend-dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www:rw
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/public
      - CI_ENVIRONMENT=development
    stdin_open: true
    networks:
      - commander-networking
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mikewang
      MYSQL_DATABASE: commanderdb
      MYSQL_PASSWORD: mikewang
    networks:
      - commander-networking
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mikewang
    networks:
      - commander-networking
  # Client need copy package to backend
  webllm:
    image: node:latest
    working_dir: "/home/node/app/webllm"
    stdin_open: true
    volumes: 
      - ./:/home/node/app
    ports:
      - "8080:8080"

networks:
  commander-networking:

volumes:
  db_data: