version: '3'

services:
  backend:
    build:
      context: ./dockerfiles
      dockerfile: backend-dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www:rw
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/public
      - CI_ENVIRONMENT=development
    stdin_open: true
